In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
filepath = "E:\PyCharmProject\SPWSYN3.1\evaluation\SVM.xlsx"
data_frame=pd.read_excel(filepath, usecols="B:J")
#新建一个工作簿
data = []
#print(data_frame)
for indexs in data_frame.index:
    data.append(indexs)
    data[indexs]=[]
    t = len(data_frame.loc[indexs].values[:])
    for i in range(t):
        data[indexs].append(data_frame.loc[indexs].values[i])
data = np.array(data)
print(data)

[[0.869 0.993 0.98  0.866 0.974 0.884 0.963 0.81  0.963]
 [0.884 0.993 0.98  0.881 0.974 0.886 0.962 0.821 0.965]
 [0.921 0.997 0.994 0.922 0.992 0.958 0.999 0.91  0.983]
 [0.958 0.968 0.942 0.935 0.98  0.941 0.946 0.939 0.98 ]
 [0.956 0.968 0.944 0.936 0.98  0.939 0.948 0.939 0.98 ]
 [0.987 0.987 0.99  0.989 0.996 0.987 0.985 0.989 0.998]
 [0.954 0.975 0.975 0.896 0.92  0.958 0.966 0.892 0.972]
 [0.954 0.975 0.975 0.896 0.917 0.957 0.965 0.891 0.972]
 [0.988 0.988 0.986 0.977 0.972 0.991 0.988 0.955 0.99 ]
 [0.108 0.207 0.644 0.162 0.551 0.299 0.03  0.327 0.349]
 [0.34  0.377 0.584 0.332 0.485 0.408 0.132 0.309 0.435]
 [0.926 0.938 0.928 0.923 0.906 0.938 0.943 0.917 0.946]
 [1.    1.    1.    1.    1.    1.    1.    1.    1.   ]
 [1.    1.    1.    1.    1.    1.    1.    1.    1.   ]
 [1.    1.    1.    1.    1.    1.    1.    1.    1.   ]
 [0.892 0.885 0.852 0.91  0.898 0.914 0.896 0.824 0.911]
 [0.897 0.894 0.878 0.922 0.89  0.922 0.894 0.828 0.908]
 [0.947 0.954 0.935 0.967 0.957

In [8]:
#print(data.shape[0])
num1 = np.zeros((3,8), dtype=np.int)
num2 = np.zeros((3,8), dtype=np.int)
num3 = np.zeros((3,8), dtype=np.int)
#print(num1)
for i in range(data.shape[0]):
    k = i%3
    #print(k)
    for j in range(data.shape[1]-1):
        if data[i][j] > data[i][8]:
            num1[k][j] = num1[k][j] + 1
        elif data[i][j] < data[i][8]:
            num2[k][j] = num2[k][j] + 1
        else:
            num3[k][j] = num3[k][j] + 1
print(num1)
print(num2)
print(num3)

[[1 5 6 2 4 1 2 0]
 [1 5 6 3 5 1 1 0]
 [0 3 1 2 4 2 4 0]]
[[17 14 13 17 14 17 15 18]
 [17 14 13 16 13 17 17 18]
 [16 15 15 14 14 14 13 18]]
[[2 1 1 1 2 2 3 2]
 [2 1 1 1 2 2 2 2]
 [4 2 4 4 2 4 3 2]]


F:\Anaconda\envs\oversampling\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  
F:\Anaconda\envs\oversampling\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional in

In [9]:
filepath = "E:\PyCharmProject\SPWSYN3.1\evaluation\LR.xlsx"
data_frame=pd.read_excel(filepath, usecols="B:J")
#新建一个工作簿
data = []
#print(data_frame)
for indexs in data_frame.index:
    data.append(indexs)
    data[indexs]=[]
    t = len(data_frame.loc[indexs].values[:])
    for i in range(t):
        data[indexs].append(data_frame.loc[indexs].values[i])
data = np.array(data)
print(data)

[[0.832 0.956 0.946 0.824 0.619 0.828 0.864 0.705 0.906]
 [0.84  0.958 0.95  0.831 0.618 0.835 0.874 0.709 0.916]
 [0.889 0.981 0.975 0.886 0.689 0.886 0.9   0.782 0.929]
 [0.905 0.967 0.947 0.912 0.971 0.912 0.946 0.9   0.926]
 [0.905 0.968 0.949 0.913 0.97  0.912 0.947 0.902 0.926]
 [0.948 0.979 0.972 0.938 0.986 0.952 0.968 0.934 0.961]
 [0.903 0.934 0.934 0.834 0.666 0.917 0.919 0.812 0.928]
 [0.904 0.938 0.937 0.833 0.652 0.919 0.918 0.803 0.929]
 [0.943 0.94  0.939 0.879 0.66  0.959 0.957 0.874 0.971]
 [0.954 0.959 0.952 0.955 0.879 0.961 0.964 0.911 0.967]
 [0.957 0.962 0.955 0.957 0.878 0.964 0.966 0.91  0.969]
 [0.966 0.968 0.969 0.971 0.918 0.974 0.983 0.959 0.965]
 [1.    1.    1.    1.    1.    1.    1.    1.    1.   ]
 [1.    1.    1.    1.    1.    1.    1.    1.    1.   ]
 [1.    1.    1.    1.    1.    1.    1.    1.    1.   ]
 [0.859 0.852 0.806 0.849 0.687 0.844 0.858 0.79  0.859]
 [0.874 0.871 0.829 0.873 0.676 0.868 0.876 0.781 0.875]
 [0.923 0.922 0.857 0.908 0.775

In [10]:
#print(data.shape[0])
num1 = np.zeros((3,8), dtype=np.int)
num2 = np.zeros((3,8), dtype=np.int)
num3 = np.zeros((3,8), dtype=np.int)
#print(num1)
for i in range(data.shape[0]):
    k = i%3
    #print(k)
    for j in range(data.shape[1]-1):
        if data[i][j] > data[i][8]:
            num1[k][j] = num1[k][j] + 1
        elif data[i][j] < data[i][8]:
            num2[k][j] = num2[k][j] + 1
        else:
            num3[k][j] = num3[k][j] + 1
print(num1)
print(num2)
print(num3)

[[2 7 5 2 2 3 5 0]
 [2 6 5 2 3 3 5 0]
 [1 5 5 2 1 3 4 1]]
[[14 11 13 16 17 15 12 18]
 [15 12 13 16 16 15 11 18]
 [13 11 13 14 18 13 12 15]]
[[4 2 2 2 1 2 3 2]
 [3 2 2 2 1 2 4 2]
 [6 4 2 4 1 4 4 4]]


F:\Anaconda\envs\oversampling\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  
F:\Anaconda\envs\oversampling\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional in